import type React from "react";
import type { LevelMeta } from "./wizardTypes";

export const C = {
  primary: "#1a699f",
  primaryDark: "#155580",
  primaryDarker: "#0d3f61",
  tealLight: "#e6f3f9",
  tealMedium: "#b8dcee",
  tealPale: "#f0f8fc",
  white: "#ffffff",
  text: "#0f172a",
  textSub: "#475569",
  textMuted: "#94a3b8",
  border: "#e2e8f0",
  borderFocus: "#1a699f",
  success: "#0f766e",
  successLight: "#ccfbf1",
  amber: "#b45309",
  amberBg: "#fef3c7",
  bg: "#f0f8fc",
};

export const LEVEL_META: Record<number, LevelMeta> = {
  1: { label: "Top Level", color: "#b91c1c", bg: "#fee2e2" },
  2: { label: "Senior", color: "#b45309", bg: "#fef3c7" },
  3: { label: "Middle", color: C.primary, bg: C.tealLight },
  4: { label: "Staff", color: "#0f766e", bg: "#ccfbf1" },
  5: { label: "External", color: "#6d28d9", bg: "#ede9fe" },
};

export const S: Record<string, React.CSSProperties> = {
  root: {
    display: "flex",
    height: "100vh",
    fontFamily: "'Inter', 'Segoe UI', sans-serif",
    overflow: "hidden",
    background: C.bg,
  },
  aside: {
    width: 248,
    flexShrink: 0,
    background: `linear-gradient(165deg, ${C.primaryDarker} 0%, ${C.primaryDark} 55%, ${C.primary} 100%)`,
    padding: "30px 20px",
    display: "flex",
    flexDirection: "column",
    color: "#fff",
    overflow: "auto",
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 38,
    color: "#fff",
  },
  brandDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: C.tealMedium,
    flexShrink: 0,
  },
  stepDot: {
    width: 26,
    height: 26,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    flexShrink: 0,
    transition: "all .3s",
  },
  liveCard: {
    background: "rgba(255,255,255,.1)",
    border: "1px solid rgba(255,255,255,.15)",
    borderRadius: 12,
    padding: 16,
    marginTop: 20,
  },
  pill: {
    fontSize: 11,
    fontWeight: 500,
    color: "rgba(255,255,255,.75)",
    background: "rgba(255,255,255,.12)",
    borderRadius: 20,
    padding: "2px 9px",
  },
  main: {
    flex: 1,
    overflow: "auto",
    padding: "40px 52px",
    position: "relative",
    isolation: "isolate",
  },
  eyebrow: {
    fontSize: 11,
    fontWeight: 700,
    color: C.textMuted,
    letterSpacing: 1.3,
    textTransform: "uppercase",
  },
  progressTrack: {
    height: 4,
    background: C.tealMedium,
    borderRadius: 2,
  },
  progressFill: {
    height: "100%",
    borderRadius: 2,
    background: C.primary,
    transition: "width .4s ease",
  },
  h1: {
    fontSize: 27,
    fontWeight: 800,
    color: C.primary,
    margin: "0 0 8px",
    letterSpacing: -0.5,
  },
  sub: {
    color: C.textSub,
    fontSize: 14,
    margin: "0 0 26px",
    lineHeight: 1.65,
  },
  input: {
    width: "100%",
    padding: "11px 13px",
    borderRadius: 10,
    outline: "none",
    border: `1.5px solid ${C.border}`,
    fontSize: 14,
    color: C.text,
    background: C.white,
    transition: "border-color .15s, box-shadow .15s",
  },
  listRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    background: C.white,
    border: `1.5px solid ${C.border}`,
    borderRadius: 10,
    padding: "11px 14px",
  },
  inlineInput: {
    flex: 1,
    border: "none",
    outline: "none",
    fontSize: 14,
    fontWeight: 500,
    color: C.text,
    fontFamily: "inherit",
    background: "transparent",
  },
  chip: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    background: C.tealPale,
    border: `1.5px solid ${C.tealMedium}`,
    borderRadius: 8,
    padding: "6px 10px",
    cursor: "default",
    transition: "background .13s, border-color .13s",
  },
  chipRm: {
    background: "none",
    border: "none",
    color: C.textMuted,
    cursor: "pointer",
    padding: 0,
    display: "flex",
    alignItems: "center",
  },
  rmBtn: {
    background: "none",
    border: "none",
    color: C.textMuted,
    cursor: "pointer",
    padding: "2px 4px",
    display: "flex",
    alignItems: "center",
    borderRadius: 4,
  },
  addBtn: {
    display: "flex",
    alignItems: "center",
    padding: "11px 18px",
    borderRadius: 10,
    border: `1.5px dashed ${C.primary}`,
    background: C.tealLight,
    color: C.primary,
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background .15s",
    fontFamily: "inherit",
  },
  successBox: {
    display: "flex",
    alignItems: "center",
    padding: "11px 15px",
    background: C.tealPale,
    border: `1px solid ${C.tealMedium}`,
    borderRadius: 8,
    fontSize: 13,
    color: C.primaryDark,
    fontWeight: 500,
  },
  btnBack: {
    padding: "11px 22px",
    borderRadius: 10,
    border: `1.5px solid ${C.border}`,
    background: C.white,
    color: C.textSub,
    fontSize: 14,
    fontWeight: 500,
    cursor: "pointer",
    transition: "background .15s, border-color .15s",
  },
  btnPrimary: {
    padding: "11px 28px",
    borderRadius: 10,
    border: "none",
    background: C.primary,
    color: C.white,
    fontSize: 14,
    fontWeight: 700,
    transition: "background .15s",
  },
  btnLaunch: {
    padding: "11px 28px",
    borderRadius: 10,
    border: "none",
    background: C.success,
    color: C.white,
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    transition: "background .15s, filter .15s",
  },
};
