"""Video-based face enrollment constants."""

__all__ = [
    "MAX_ENROLLMENT_FRAMES", "MIN_ENROLLMENT_FRAMES", "OPTIMAL_FACES_PER_VIDEO",
    "MIN_VIDEO_DURATION", "MAX_VIDEO_DURATION",
]

MAX_ENROLLMENT_FRAMES = 120
MIN_ENROLLMENT_FRAMES = 10
OPTIMAL_FACES_PER_VIDEO = 40
MIN_VIDEO_DURATION = 5    # Seconds
MAX_VIDEO_DURATION = 300  # Seconds (5 minutes)
