"""Multi-frame face tracking constants (used by the live recognition loop)."""

__all__ = [
    "TRACK_MAX_AGE_SECONDS", "TRACK_ACTIVE_IOU_THRESHOLD", "TRACK_LOST_IOU_THRESHOLD",
    "TRACK_ACTIVE_DIST_FACTOR", "TRACK_LOST_DIST_FACTOR",
    "TRACK_ACTIVE_MIN_DIST", "TRACK_LOST_MIN_DIST",
    "TRACK_UNKNOWN_RETRY_INTERVAL", "TRACK_AI_INTERVAL",
]

TRACK_MAX_AGE_SECONDS = 5.0
TRACK_ACTIVE_IOU_THRESHOLD = 0.15
TRACK_LOST_IOU_THRESHOLD = 0.1
TRACK_ACTIVE_DIST_FACTOR = 0.8
TRACK_LOST_DIST_FACTOR = 0.2
TRACK_ACTIVE_MIN_DIST = 80
TRACK_LOST_MIN_DIST = 40
TRACK_UNKNOWN_RETRY_INTERVAL = 0.1
TRACK_AI_INTERVAL = 0.05
